export default {
  WELCOME: require("./welcome.png"),
  LAYER: require('./layerIcon.png'),
  STAR: require('./star.png'),
  PROFILE: require('./profile.png'),
  CART: require("./cartIcon.png"),
  FACEBOOK: require('./facebook.png'),
  GOOGLE: require('./google.png'),
  TACOS: require('./tacos.png'),
  BURGER: require('./burger.png'),
  BURITOS: require("./buritos.png"),
  FRIES: require('./fries.png'),
  PIZZA: require('./pizza.png'),
  DRINK1: require('./drink1.png'),
  DRINK2: require('./drink2.png'),
  POPULARPIZZA: require('./popularPizza.png'),
  POPULARBURGER: require('./popularBurger.png'),
  IMAGE_BACKGROUND: require('./background-detail.png'),
  MAP_MARKER: require('./map-marker.png'),
  LOGO_APP:require('./logoapp.png')
}